services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - bad-server_db:/data/db  # Используем правильное имя volume
    ports:
      - 27017:27017
    networks:
      - internal_dev

  nginx-dev:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/var/app:ro
    depends_on:
      - mongo
    networks:
      - internal_dev

volumes:
  bad-server_db:
    external: true  # Используем существующий volume

networks:
  internal_dev:
    driver: bridge